apiVersion: batch/v1
kind: Job
metadata:
  name: ptt-client-job-1
  namespace: ptt
spec:
  ttlSecondsAfterFinished: 30
  parallelism: 4
  template:
    spec:
      containers:
      - name: ptt-client-test
        env:
        - name: TEST_PLANRUN_ID
          value: "1"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
        image: ghcr.io/2023-da-ptt/ptt-client:latest
        #
        # when deploying into production it should
        # pull the newest image but for skaffold
        # it should take the available image which
        # is going to be the one provided by skaffold
        #
        #imagePullPolicy: IfNotPresent  # Skaffold
        imagePullPolicy: Always         # Prod
      imagePullSecrets:
      - name: dockerconfigjson-github-com
      restartPolicy: Never